# 构建站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy Music2026 site to Pages

on:
  # 在针对 `main` 分支的推送上运行。
  # 如果你使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

    # 允许你从 Actions 选项卡手动运行此工作流程
    workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    # name: Build Music2026
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0

      - uses: pnpm/action-setup@v4 # 如果使用 pnpm，请取消此区域注释
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm # 或 npm / yarn
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install # 或 npm ci / pnpm install / yarn install
      - name: Build with Music2026
        run: pnpm build # 或npm run build / pnpm build / yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build website
      #   run: npm run build
      # - name: Upload Build Artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: build
  # 部署工作
  deploy:
    name: Deploy to GitHub Pages
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # permissions:
    #   pages: write # to deploy to Pages
    #   id-token: write # to verify the deployment originates from an appropriate source
